### PR TITLE
add leone as a contributor

### PR DESCRIPTION
**Pull request by darioalessandro**
Adding @leon3s as a formal contributor. 

I also sent him a write access request for this repo.

### CODE REVIEW

**Comment by leon3s** [comment]
I accepted the invitation thanks!

**Comment by leon3s** [comment]
I'll push from main repo and not from my fork if you don't mind ?
It's easier for me as i don't have to resync the forked repo everytime

**Comment by darioalessandro** [comment]
For sure!! the goal of this MR is to show you as a core contributor in the README, even when it will also show on the right.

**Comment by darioalessandro** [comment]
Screen Shot 2023-06-11 at 2 53 44 PM

**Review by leon3s — APPROVED** [review]
Thanks!

**Pull request merged**
